version: '3.8'
name: production
services:
  responsive-front-prod:
    container_name: responsive-front-prod
    image: anicmarko9/responsive-front-prod:1.0
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - prod
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production
networks:
  prod:
    name: prod
